<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIzxS1e3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIzxS1e3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIzxS1e3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIzxS1e3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIzxS1e3\App_KernelDevDebugContainer([
    'container.build_hash' => 'IzxS1e3',
    'container.build_id' => '85a6e5f7',
    'container.build_time' => 1703922906,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIzxS1e3');
